# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6463a38ddaf436cc44dafd467ac5a6ce6363ed981fd0b0df25b955af33eb1e47475e3db98be3a680f6f8c3c97afd2c83a2f5a540bddca134732d550f3269e2

test:
  secret_key_base: e77b25c7029bd10e1fe0ab63dbf9f8b217c2309514ebe0bc51e9a88953a76cf5a22d5b4241f5db101572af608a98a65d95054db223d2a44a0d8dc0be8bd58299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
